🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/mouse-toggle b/bin/mouse-toggle
--- a/bin/mouse-toggle
+++ b/bin/mouse-toggle
@@ -1,23 +1,87 @@
 #!/usr/bin/env bash
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="mouse-toggle"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
-if [[ -n $TMUX ]]; then
-  if [[ -z "$(tmux show-options -gw mouse | grep off)" ]]; then
-    tmux set-option -gq mouse-utf8 off
-    tmux set-option -gq mouse-resize-pane off
-    tmux set-option -gq mouse-select-pane off
-    tmux set-option -gq mouse-select-window off
-    tmux set-window-option -gq mouse off
-    tmux display-message "Mouse: OFF"
-  else
-    tmux set-option -gq mouse-utf8 on
-    tmux set-option -gq mouse-resize-pane on
-    tmux set-option -gq mouse-select-pane on
-    tmux set-option -gq mouse-select-window on
-    tmux set-window-option -gq mouse on
-    tmux display-message "Mouse: ON"
-  fi
-  exit 0
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version       : 031520212018-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : mouse-toggle --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Monday, Mar 15, 2021 20:18 EDT
+# @File          : mouse-toggle
+# @Description   : tmux script to turn mouse on/off
+# @TODO          :
+# @Other         :
+# @Resource      :
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
 else
-  echo "not tmux session"
-  exit 1
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
 fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: mouse-toggle  -  mouse-toggle --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  if [[ -n "$TMUX" ]]; then
+    if [[ -z "$(tmux show-options -gw mouse | grep off)" ]]; then
+      tmux set-option -gq mouse-utf8 off
+      tmux set-option -gq mouse-resize-pane off
+      tmux set-option -gq mouse-select-pane off
+      tmux set-option -gq mouse-select-window off
+      tmux set-window-option -gq mouse off
+      tmux display-message "Mouse: OFF"
+    else
+      tmux set-option -gq mouse-utf8 on
+      tmux set-option -gq mouse-resize-pane on
+      tmux set-option -gq mouse-select-pane on
+      tmux set-option -gq mouse-select-window on
+      tmux set-window-option -gq mouse on
+      tmux display-message "Mouse: ON"
+    fi
+  exitCode=0
+  else
+    printf_red "This doesn't seem to be a tmux session"
+    exitCode=0
+  fi
+  return "${exitCode:-$?}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
+
